import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./Components/Navbar/Navbar";
import "./globals.css";
import { StoreProvider } from "./store/storeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          
          <Navbar/>
          
          
          
          {children}
          <footer className="bg-slate-900 text-white p-4 text-center">
            codevolution
          </footer>
        </body>
      </html>
    </StoreProvider>
  );
}
